### ISSUE TITLE
Cannot edit content

### ISSUE THREAD

**Issue by dsdsdsdsdsds** [wobsoriano/lexical-vue#11]
I’m not sure if I miss something obvious, but I’m unable to actually add/edit content on Nuxt 3: `contenteditable` stays always `false`.

I followed your example in the docs and also had a look at https://github.com/wobsoriano/lexical-vue/issues/4, but I can’t seem to get it work neither in my project nor in a sandbox (https://stackblitz.com/edit/nuxt-starter-bk7zmb). Any idea? Is lexical-vue compatible with lexical 0.8.1?

**Comment by atif0075** [comment]
Also happened to me in vue 3

**Comment by toniengelhardt** [comment]
You have to add `editable: true` to the config, then it works.

**Comment by wobsoriano** [comment]
as @toniengelhardt , you have to add `editable: true`. Thanks!
