### ISSUE TITLE
The interface is not generating.

### ISSUE THREAD

**Issue by sksaaa** [wobsoriano/lexical-vue#18]
![image](https://github.com/wobsoriano/lexical-vue/assets/85176538/7a5a5e3d-6a61-4218-8713-d70e2e0fdebe)
I am using sample code, but the rich text is not displaying correctly.
Thanks 🙏🏽

**Comment by sksaaa** [comment]
> 
I'm sorry if I'm not very clear, is there a written demo I want to look at the demo and compare
![image](https://github.com/wobsoriano/lexical-vue/assets/85176538/71294074-03fb-4e11-b063-bce748a5005a)

**Comment by wobsoriano** [comment]
The [playground](https://github.com/wobsoriano/lexical-vue/blob/main/playground/src/components/Editor.vue) app should help you get started! 😄
