### ISSUE TITLE
Node Overrides causes type error in "initialConfig".

### ISSUE THREAD

**Issue by vj-kimura** [wobsoriano/lexical-vue#19]
Official sample code
https://lexical.dev/docs/concepts/node-replacement

```
const editorConfig = {
    ...
    nodes=[
        // Don't forget to register your custom node separately!
        CustomParagraphNode,
        {
            replace: ParagraphNode,
            with: (node: ParagraphNode) => {
                return new CustomParagraphNode();
            }
        }
    ]
}
```

I tried this code in lexical-vue, but it caused a type error in `initialConfig`.

<img width="394" alt="スクリーンショット 2023-06-21 19 02 00" src="https://github.com/wobsoriano/lexical-vue/assets/105843678/e3dd4478-a6c6-4fb7-846b-bbdec126f728">

I think the reason is that lexical-vue does not define `replace` in `Nodes`.
...Or is there any way to work around this error?

----
lexical-vue
[src/components/LexicalComposer.vue](https://github.com/wobsoriano/lexical-vue/blob/main/src/components/LexicalComposer.vue)

```
const props = defineProps<{
  initialConfig: {
    namespace?: string
    nodes?: Class<LexicalNode>[]
    editable?: boolean
    theme?: EditorThemeClasses
    editorState?: InitialEditorStateType
  }
}>()
```
----
Origin (lexical-react)
https://github.com/facebook/lexical/blob/main/packages/lexical-react/src/LexicalComposer.tsx

```
export type InitialConfigType = Readonly<{
  editor__DEPRECATED?: LexicalEditor | null;
  namespace: string;
  nodes?: ReadonlyArray<
    | Klass<LexicalNode>
    | {
        replace: Klass<LexicalNode>;
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        with: <T extends {new (...args: any): any}>(
          node: InstanceType<T>,
        ) => LexicalNode;
      }
  >;
  onError: (error: Error, editor: LexicalEditor) => void;
  editable?: boolean;
  theme?: EditorThemeClasses;
  editorState?: InitialEditorStateType;
}>;
```

**Comment by wobsoriano** [comment]
Copied the react package types for node. Can you check if it's fixed?

**Comment by vj-kimura** [comment]
It looks like it's working correctly!
There is no error.

<img width="833" alt="スクリーンショット 2023-06-24 22 28 22" src="https://github.com/wobsoriano/lexical-vue/assets/105843678/3662fb82-7641-4669-a0a1-0015c9afab94">

**Comment by wobsoriano** [comment]
Cool! Closing this now 😉

**Comment by vj-kimura** [comment]
Thank you!
