### ISSUE TITLE
Two lexical.dev.js!

### ISSUE THREAD

**Issue by aquarius-wing** [wobsoriano/lexical-vue#2]
I run `npm i` and find this in
```
- node_modules
  - ...
 - lexical-vue
    - dist
    - node_modules
      - lexical
        - **Lexical.dev.js**
```
This BUG makes my program can not get current EditorState.
Because read EditorState through `lexical-vue`, it will load `Lexical.dev.js` file in `lexical-vue`
And then read EditorState through `lexical`, it will load `Lexical.dev.js` file in `lexical`,it turns out get error.
If I use `pnpm i`, then there is only dist dir in lexical-vue.
My env
- node@v14.19.1
- npm@6.14.16
- Windows 11 21H2

**Comment by wobsoriano** [comment]
https://discord.com/channels/953974421008293909/956476669600862218/988354607493304320
