### ISSUE TITLE
[Plugin Request] Mentions

### ISSUE THREAD

**Issue by HapLifeMan** [wobsoriano/lexical-vue#31]
Hello @wobsoriano,

Congrats for this work! Would you consider adding the [MentionsPlugin](https://github.com/facebook/lexical/blob/20123bfb98632889701746ee424f70442be0e9be/packages/lexical-playground/src/plugins/MentionsPlugin/index.tsx) to this library?
Not sure about all the work it implies...

Thank you very much! 🙏🏻

**Comment by wobsoriano** [comment]
Released this in v0.8.0 🎆
