### ISSUE TITLE
Is it possible to work with Nuxt3?

### ISSUE THREAD

**Issue by nsefh** [wobsoriano/lexical-vue#4]
Hello, I really liked the framework.

But there was a need to use with Nuxt3. I am not very versed in JS and do not understand the essence of the error.

I copied the example code into the component, but I get an error:
[h3] [unhandled] H3Error: Class extends value undefined is not a constructor or null

**Comment by wobsoriano** [comment]
h3 error is unrelated to lexical. Do you have a simple reproduction? Try stackblitz

**Comment by nsefh** [comment]
> h3 error is unrelated to lexical. Do you have a simple reproduction? Try stackblitz

Thanks for the answer.
https://stackblitz.com/edit/github-rsrbgs?embed=1&file=components/TextEditor.vue

**Comment by nsefh** [comment]
Accidentally closed the issue. Unfortunately the question is open.

**Comment by wobsoriano** [comment]
Thanks for the repro! I'll check in a bit

**Comment by wobsoriano** [comment]
Still investigating what causes the issue

**Comment by kylegl** [comment]
I was getting this error in vue when I had lexical and lexical-vue installed as dev dependencies. Moved them to dependencies and the error is gone. Not sure if that helps with Nuxt.

**Comment by wobsoriano** [comment]
Tried it on `Nuxt 3.0.0-rc.12` today and got it working. Just wrap your main Editor component in a `<ClientOnly />` component.
