### ISSUE TITLE
How to use LexicalTypeaheadMenuPlugin

### ISSUE THREAD

**Issue by foodEat** [wobsoriano/lexical-vue#46]
I want use LexicalTypeaheadMenuPlugin but your document not provide usage

**Comment by wobsoriano** [comment]
You can check the mentions plugin in the playground as basis for now

https://github.com/wobsoriano/lexical-vue/blob/7e9284838080c4bde27e7f7411b549b166573ca5/playground/src/plugins/MentionsPlugin.vue#L605

**Comment by foodEat** [comment]
Thanks I have find this plugin
