### ISSUE TITLE
Npm miss LexicalAutoEmbedPlugin directory in components directory

### ISSUE THREAD

**Issue by foodEat** [wobsoriano/lexical-vue#47]
I found that the code on NPM is missing the LexicalAutoEmbedPlugin directory. LexicalAutoEmbedPlugin exists in the directory I built locally
![image](https://github.com/wobsoriano/lexical-vue/assets/39737398/5c476d2a-5973-45b4-bea4-24a519fa1222)
<img width="389" alt="image" src="https://github.com/wobsoriano/lexical-vue/assets/39737398/fb320ca2-3bc7-44d8-8f32-cf290768c330">

**Comment by wobsoriano** [comment]
Would you like to open a PR?

**Comment by wobsoriano** [comment]
This is exported in latest versions
