### ISSUE TITLE
Error in LexicalTypeaheadMenuPlugin in new vue version

### ISSUE THREAD

**Issue by luugiavinh** [wobsoriano/lexical-vue#62]
I found an error when using LexicalTypeaheadMenuPlugin in newer vue version (^3.4.32). There is an additional text node before the menu. 

I think it's something related to the teleport which is provided in the sample code. Everything work fine for vue version below 3.4.32.  I also checked that the release version 3.4.32 have modify something related to Teleport. The second screenshot is what i founded related to Teleport update

The current code is select the firstChild of the containerDiv which lead to select the text node instead of my menu.
![image](https://github.com/user-attachments/assets/c1f429e2-b538-4520-868d-87dd9b2d8924)
![image](https://github.com/user-attachments/assets/a815dbac-8a33-4dc4-ad5e-ee82b9129571)
![image](https://github.com/user-attachments/assets/ebd267dd-902b-438a-b537-b32f393fd6b6)
![image](https://github.com/user-attachments/assets/176f294f-82e2-404b-8852-553e4c763c70)

**Comment by wobsoriano** [comment]
Thanks @Deuscx
