### ISSUE TITLE
Collaborative feature

### ISSUE THREAD

**Issue by mortegro** [wobsoriano/lexical-vue#7]
Thanks for this great library! Is it by any chance possible to integrate the collaborative features to sync the editor state using yjs like in the react CollaborationPlugin?

**Comment by wobsoriano** [comment]
Yes! We just need to convert this component to Vue https://github.com/facebook/lexical/blob/main/packages/lexical-react/src/LexicalCollaborationPlugin.ts

**Comment by zswaff** [comment]
Assuming nobody is working on this, my team and I are going to open a PR for this in the coming week or two

**Comment by wobsoriano** [comment]
That’d be great @zswaff !
